---
title: "linear_regression_lab"
author: "Daniel Urimubenshi"
date: "2026-08-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ISLR2)
head(Boston)
```
### Simple linear Regression

```{r}
lm.fit <- lm(medv ~ lstat, data = Boston)
attach(Boston)

coef(lm.fit)
confint(lm.fit)
```

```{r}
predict(lm.fit, data.frame(lstat = (c(5, 10, 15))),
interval = "confidence")
```
```{r}
 predict(lm.fit, data.frame(lstat = (c(5, 10, 15))),
interval = "prediction")
```
```{r}
plot(lstat, medv)
abline(lm.fit)
abline(lm.fit, lwd = 3)
abline(lm.fit, lwd = 3, col = "red")
```
```{r}

plot(lstat, medv, col = "red")
plot(lstat, medv, pch = 20)
plot(lstat, medv, pch = "+")
plot(1:20, 1:20, pch = 1:20)
```
```{r}
par(mfrow = c(2, 2))
plot(lm.fit)
```



```{r}
plot(predict(lm.fit), residuals(lm.fit))
plot(predict(lm.fit), rstudent(lm.fit))
```
### Multiple linear regression

```{r}
lm.fit <- lm(medv ~ lstat + age, data = Boston)
summary(lm.fit)
```
```{r}
lm.fit <- lm(medv ~ ., data = Boston)
summary(lm.fit)
```

